# specifies the JVM (Java Virtual Machine) arguments used for the Gradle Daemon.
# These arguments control various aspects of the JVM's behavior, such as memory allocation and performance tuning
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g
# CHEATSHEET:
# MEMORY ALLOCATION:
# -Xmx: Maximum heap size.
# -Xms: Initial heap size.
# -XX:MaxPermSize: Maximum size for the permanent generation

# GARBAGE COLLECTION:
# -XX:+UseG1GC: Use the G1 garbage collector.
# -XX:+UseParallelGC: Use the parallel garbage collector.
# -XX:+UseConcMarkSweepGC: Use the concurrent mark-sweep garbage collector.

# Other Performance Tuning:
# -Dfile.encoding=UTF-8: Set the file encoding.
# -Duser.country=US: Set the user country (locale).
# -Duser.language=en: Set the user language (locale).


##################################
# Jetifier is a tool that helps in migrating libraries that are using the old Android Support Library to the new AndroidX library
android.enableJetifier=true
android.useAndroidX=true

# Property used in the gradle.properties file to control the behavior of the R8 compiler in Android projects
android.enableR8.fullMode=true

#  allows for non-final resource IDs in your Android project
#  This is particularly useful for applications using dynamic feature modules or for projects that need to modify resources at runtime
android.nonFinalResIds=true

#  controls whether the R class generated for your Android project is transitive or non-transitive
#  By default, Android projects generate a transitive R class, which means that resources from dependencies are included in the R class of your application module.
#  This can lead to unnecessary resource references and larger APK sizes.
android.nonTransitiveRClass=true

# Disable "The option setting 'android.enableUnitTestBinaryResources=true' is experimental and unsupported" warning
android.suppressUnsupportedOptionWarnings=true

# enables parallel project execution in Gradle builds.
# When enabled, Gradle will attempt to run multiple projects in parallel
# can significantly speed up the build process, especially in multi-module projects.
org.gradle.parallel=true

#  enables the Gradle build cache.
#  The build cache allows Gradle to reuse outputs from previous builds
#  reduces build time by avoiding unnecessary work.
org.gradle.caching=true

# controls whether the Gradle Daemon is enabled.
# The Gradle Daemon is a long-lived background process
# that can significantly improve the performance of Gradle builds by avoiding the startup costs of launching a new JVM for each build
org.gradle.daemon=true

#  file that enables the experimental Gradle Configuration Cache feature.
#  The Configuration Cache aims to reduce build times by caching the result of the configuration phase and reusing it in subsequent builds
org.gradle.configuration-cache=true
org.gradle.unsafe.configuration-cache=true

# used to enable Gradle Build Scans, which provide detailed insights into your build process. Build Scans capture and analyze build data
# including performance metrics, build failures, and configuration details.
# They help diagnose build issues, understand build performance, and share build information with team members
org.gradle.scan=true

# CONFIGURATION CACHE PROBLEMS = WARN:
# setting used to configure the handling of issues related to the Gradle Configuration Cache
# Use this flag carefully, in case some of the plugins are not fully compatible.
org.gradle.configuration-cache.problems=warn

# Increase timeouts for network requests
# specifies the connection timeout for HTTP requests made by Gradle.
# This timeout controls how long Gradle will wait for a connection to be established before timing out.
org.gradle.internal.http.connectionTimeout=120000

# Increase timeouts for network requests
#  specifies the socket timeout for HTTP requests made by Gradle.
#  The socket timeout determines how long Gradle will wait for data to be read from a server after a connection has been established
org.gradle.internal.http.socketTimeout=120000