plugins {
    id 'com.android.application'
}

android {
    namespace 'io.hifii.drawertest'
    compileSdkPreview 'UpsideDownCake'

    defaultConfig {
        applicationId "io.hifii.drawertest"
        minSdk 30
        targetSdkVersion defaultTargetSdkVersion
        versionCode 1
        versionName "0.0.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
    }
    buildToolsVersion '34.0.0 rc2'
}

dependencies {
    implementation 'androidx.appcompat:appcompat:+'
    implementation 'com.google.android.material:material:+'
    implementation 'androidx.constraintlayout:constraintlayout:+'
    implementation 'androidx.navigation:navigation-fragment:+'
    implementation 'androidx.navigation:navigation-ui:+'
    implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.0"))
    testImplementation 'junit:junit:+'
    androidTestImplementation 'androidx.test.ext:junit:+'
    androidTestImplementation 'androidx.test.espresso:espresso-core:+'
 }