plugins {
    id 'com.android.application'
}

static def getDate() {
    new Date().format('MM-dd-yyyy-HHmm')
}

android {
    namespace 'io.hifii.drawertest'
    compileSdk 35

    defaultConfig {
        applicationId "io.hifii.drawertest"
        minSdk 31
        targetSdk 35
        versionCode 1
        versionName "0.0.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        android.applicationVariants.configureEach { variant ->
            variant.outputs.all {
                outputFileName = "MD3-Drawer-${getDate()}.apk"
            }
        }
        release {
            minifyEnabled true
            shrinkResources true
            buildConfigField("String", "BUILD_TIME", "\"0\"")
            resValue("string", "build_time", "0")
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro', 'gson.pro'
        }
        debug {
            minifyEnabled false
            shrinkResources false
            debuggable true
            buildConfigField("String", "BUILD_TIME", "\"0\"")
            resValue("string", "build_time", "0")
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        // encoding "UTF-8"
        encoding 'utf-8'
        incremental true
        coreLibraryDesugaringEnabled true
    }
    buildFeatures {
        buildConfig = true
        viewBinding = true
        dataBinding = true
        resValues = true

        // Disable some unused things
        compose = false
        aidl = false
        renderScript = false
        shaders = false
    }
    androidResources {
        lintOptions {
            // Turns on checks for the issue IDs you specify. These checks are in
            // addition to the default lint checks.
            enable 'RtlHardcoded', 'RtlCompat', 'RtlEnabled'

            // To enable checks for only a subset of issue IDs and ignore all others,
            // list the issue IDs with the 'check' property instead. This property overrides
            // any issue IDs you enable or disable using the properties above.
            checkOnly 'NewApi', 'InlinedApi'

            // suppress false warning ("Resource IDs will be non-final in Android Gradle Plugin version
            // 5.0, avoid using them in switch case statements"), which affects only library projects
            disable 'NonConstantResourceId'

            disable 'MissingDefaultResource'

            // Disable lint check for missing default resource
            disable 'MissingDefaultResource'

            ignore "ObsoleteSdk", "UnusedImports"

            // Turns off checks for the issue IDs you specify.
            disable 'TypographyFractions', 'TypographyQuotes'

            // Kotlin related check that might be annoying
            disable "CheckResult"

            // If you're using localization libraries
            disable "SetTextI18n"

            // If set to true, turns off analysis progress reporting by lint.
            quiet true

            // if set to true (default), stops the build if errors are found.
            abortOnError false

            // if true, only report errors.
            ignoreWarnings true

            checkReleaseBuilds false
        }
    }
}

dependencies {
    def activity_version = '1.9.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.8.4'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.4'
    implementation 'androidx.navigation:navigation-fragment:2.7.7'
    implementation 'androidx.navigation:navigation-ui:2.7.7'
    testImplementation 'junit:junit:4.13.2'
    implementation "androidx.activity:activity:$activity_version"
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.4'
}